version: '3.2'

services:

  campaign-cli:
    build:
      context: ./campaign-cli
      args:
        SERVICE: campaign
    environment:
      MICRO_REGISTRY: "mdns"

  user-cli:
    build:
      context: ./user-cli
      args:
        SERVICE: user
    environment:
      MICRO_REGISTRY: "mdns"
