version: '3.2'

services:

  #
  # Postgresql Service
  #
  postgres:
    image: hausgold/postgres
    ports:
      - 5432:5432
    volumes:
      - type: bind
        source: ./postgres_data
        target: /var/lib/postgresql/data
    environment:
      MDNS_HOSTNAME: postgres.local
      POSTGRES_USER: fc
      POSTGRES_PASSWORD: fcpass
      POSTGRES_DB: fc

  #
  # Campaign Service
  #
  campaign-service:
    build:
      context: ./campaign-service
      args:
        SERVICE: campaign
    ports:
    - 50051:50051
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_HOST: "postgres"
      DB_USER: "fc"
      DB_PASS: "fcpass"
      DB_NAME: "fc"

  #
  # Venue Service
  #
  venue-service:
    build:
      context: ./venue-service
      args:
        SERVICE: venue
    ports:
    - 50052:50051
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_HOST: "postgres.local"

  #
  # Account Service
  #
  account-service:
    build:
      context: account-service
      args:
        SERVICE: account
    ports:
    - 50053:50051
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
#      MICRO_BROKER: "nats"
      DB_HOST: "postgres"
      DB_USER: "fc"
      DB_PASS: "fcpass"
      DB_NAME: "fc"

  #
  # Email Service
  #
  email-service:
    build:
      context: ./email-service
      args:
        SERVICE: email
#    ports:
#    - 50053:50051
    environment:
#      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
#      MICRO_BROKER: "nats"
#      DB_HOST: "postgres"
#      DB_USER: "fc"
#      DB_PASS: "fcpass"
#      DB_NAME: "fc"

  #
  # The micro web provides a dashboard to view and query services.
  #
  # https://github.com/micro/micro/tree/master/web
  #
  microweb:
    image: microhq/micro
    command: web
    ports:
    # outer:inner
    - "8082:8082"
    environment:
      MICRO_REGISTRY: "mdns"
      MICRO_API_NAMESPACE: "fc"
      MICRO_HANDLER: "rpc"

  #
  # Go-Micro API Gateway
  #
  # https://github.com/micro/micro/tree/master/api
  #
  microapi:
    image: microhq/micro
    command: api
    ports:
      - "80:8080"
    environment:
      MICRO_REGISTRY: "mdns"
      MICRO_API_NAMESPACE: "fc"
      MICRO_HANDLER: "rpc"
#      MICRO_ENABLE_ACME: true
#      MICRO_ACME_HOSTS: "funnelcrowd.com"
#      MICRO_ENABLE_TLS: true
#      MICRO_TLS_CERT_FILE: /path/to/cert
#      MICRO_TLS_KEY_FILE: /path/to/key
