version: '3.1'

services:

  campaign-cli:
    build:
      context: ./campaign-cli
      args:
        SERVICE: campaign
    environment:
      MICRO_REGISTRY: "mdns"

  campaign-service:
    build:
      context: ./campaign-service
      args:
        SERVICE: campaign
    ports:
    - 50051:50051
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_HOST: "datastore:27017"

  venue-service:
    build:
      context: ./venue-service
      args:
        SERVICE: venue
    ports:
    - 50052:50051
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
