version: '3.2'

services:

  #
  # Postgresql Service
  #
  postgres:
    image: hausgold/postgres
    ports:
      - 5432:5432
    volumes:
      - type: bind
        source: ./postgres_data
        target: /var/lib/postgresql/data
    environment:
      MDNS_HOSTNAME: postgres.local
      POSTGRES_USER: fc
      POSTGRES_PASSWORD: fcpass
      POSTGRES_DB: fc

  #
  # Campaign Service
  #
  campaign-service:
    build:
      context: ./campaign-service
      args:
        SERVICE: campaign
    ports:
    - 50051:50051
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_HOST: "postgres"
      DB_USER: "fc"
      DB_PASS: "fcpass"
      DB_NAME: "fc"

  #
  # Venue Service
  #
  venue-service:
    build:
      context: ./venue-service
      args:
        SERVICE: venue
    ports:
    - 50052:50051
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_HOST: "postgres.local"

  #
  # User Service
  #
  user-service:
    build:
      context: ./user-service
      args:
        SERVICE: user
    ports:
    - 50053:50051
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_HOST: "postgres"
      DB_USER: "fc"
      DB_PASS: "fcpass"
      DB_NAME: "fc"
