// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/venue/venue.proto

package go_micro_srv_venue

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Venue struct {
	Id                   string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Location             string     `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	Capacity             int32      `protobuf:"varint,4,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Amenities            []*Amenity `protobuf:"bytes,5,rep,name=amenities,proto3" json:"amenities,omitempty"`
	UserId               string     `protobuf:"bytes,6,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Venue) Reset()         { *m = Venue{} }
func (m *Venue) String() string { return proto.CompactTextString(m) }
func (*Venue) ProtoMessage()    {}
func (*Venue) Descriptor() ([]byte, []int) {
	return fileDescriptor_venue_cb85b01f6919fe7d, []int{0}
}
func (m *Venue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Venue.Unmarshal(m, b)
}
func (m *Venue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Venue.Marshal(b, m, deterministic)
}
func (dst *Venue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Venue.Merge(dst, src)
}
func (m *Venue) XXX_Size() int {
	return xxx_messageInfo_Venue.Size(m)
}
func (m *Venue) XXX_DiscardUnknown() {
	xxx_messageInfo_Venue.DiscardUnknown(m)
}

var xxx_messageInfo_Venue proto.InternalMessageInfo

func (m *Venue) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Venue) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Venue) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *Venue) GetCapacity() int32 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

func (m *Venue) GetAmenities() []*Amenity {
	if m != nil {
		return m.Amenities
	}
	return nil
}

func (m *Venue) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type Amenity struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Amenity) Reset()         { *m = Amenity{} }
func (m *Amenity) String() string { return proto.CompactTextString(m) }
func (*Amenity) ProtoMessage()    {}
func (*Amenity) Descriptor() ([]byte, []int) {
	return fileDescriptor_venue_cb85b01f6919fe7d, []int{1}
}
func (m *Amenity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Amenity.Unmarshal(m, b)
}
func (m *Amenity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Amenity.Marshal(b, m, deterministic)
}
func (dst *Amenity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Amenity.Merge(dst, src)
}
func (m *Amenity) XXX_Size() int {
	return xxx_messageInfo_Amenity.Size(m)
}
func (m *Amenity) XXX_DiscardUnknown() {
	xxx_messageInfo_Amenity.DiscardUnknown(m)
}

var xxx_messageInfo_Amenity proto.InternalMessageInfo

func (m *Amenity) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Amenity) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Amenity) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Amenity) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type VenueSpecification struct {
	Location             string     `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	Capacity             int32      `protobuf:"varint,2,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Amenities            []*Amenity `protobuf:"bytes,3,rep,name=amenities,proto3" json:"amenities,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *VenueSpecification) Reset()         { *m = VenueSpecification{} }
func (m *VenueSpecification) String() string { return proto.CompactTextString(m) }
func (*VenueSpecification) ProtoMessage()    {}
func (*VenueSpecification) Descriptor() ([]byte, []int) {
	return fileDescriptor_venue_cb85b01f6919fe7d, []int{2}
}
func (m *VenueSpecification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VenueSpecification.Unmarshal(m, b)
}
func (m *VenueSpecification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VenueSpecification.Marshal(b, m, deterministic)
}
func (dst *VenueSpecification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VenueSpecification.Merge(dst, src)
}
func (m *VenueSpecification) XXX_Size() int {
	return xxx_messageInfo_VenueSpecification.Size(m)
}
func (m *VenueSpecification) XXX_DiscardUnknown() {
	xxx_messageInfo_VenueSpecification.DiscardUnknown(m)
}

var xxx_messageInfo_VenueSpecification proto.InternalMessageInfo

func (m *VenueSpecification) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *VenueSpecification) GetCapacity() int32 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

func (m *VenueSpecification) GetAmenities() []*Amenity {
	if m != nil {
		return m.Amenities
	}
	return nil
}

type Response struct {
	Venue                *Venue   `protobuf:"bytes,1,opt,name=venue,proto3" json:"venue,omitempty"`
	Venues               []*Venue `protobuf:"bytes,2,rep,name=venues,proto3" json:"venues,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_venue_cb85b01f6919fe7d, []int{3}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetVenue() *Venue {
	if m != nil {
		return m.Venue
	}
	return nil
}

func (m *Response) GetVenues() []*Venue {
	if m != nil {
		return m.Venues
	}
	return nil
}

func init() {
	proto.RegisterType((*Venue)(nil), "go.micro.srv.venue.Venue")
	proto.RegisterType((*Amenity)(nil), "go.micro.srv.venue.Amenity")
	proto.RegisterType((*VenueSpecification)(nil), "go.micro.srv.venue.VenueSpecification")
	proto.RegisterType((*Response)(nil), "go.micro.srv.venue.Response")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for VenueService service

type VenueServiceClient interface {
	FindAvailable(ctx context.Context, in *VenueSpecification, opts ...client.CallOption) (*Response, error)
}

type venueServiceClient struct {
	c           client.Client
	serviceName string
}

func NewVenueServiceClient(serviceName string, c client.Client) VenueServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "go.micro.srv.venue"
	}
	return &venueServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *venueServiceClient) FindAvailable(ctx context.Context, in *VenueSpecification, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "VenueService.FindAvailable", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for VenueService service

type VenueServiceHandler interface {
	FindAvailable(context.Context, *VenueSpecification, *Response) error
}

func RegisterVenueServiceHandler(s server.Server, hdlr VenueServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&VenueService{hdlr}, opts...))
}

type VenueService struct {
	VenueServiceHandler
}

func (h *VenueService) FindAvailable(ctx context.Context, in *VenueSpecification, out *Response) error {
	return h.VenueServiceHandler.FindAvailable(ctx, in, out)
}

func init() { proto.RegisterFile("proto/venue/venue.proto", fileDescriptor_venue_cb85b01f6919fe7d) }

var fileDescriptor_venue_cb85b01f6919fe7d = []byte{
	// 328 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0xc1, 0x4e, 0xc2, 0x40,
	0x10, 0xb5, 0x2d, 0x2d, 0x30, 0xa8, 0x87, 0xbd, 0x50, 0xd1, 0x43, 0xd3, 0x83, 0xe1, 0x54, 0x22,
	0x9e, 0x3c, 0x72, 0x31, 0xf1, 0x5a, 0x13, 0x3d, 0x9a, 0x65, 0x77, 0x24, 0x93, 0xc0, 0x6e, 0xd3,
	0x2d, 0x4d, 0xf8, 0x02, 0x3f, 0xc9, 0xdf, 0x33, 0x1d, 0xb0, 0x60, 0x44, 0x12, 0x2f, 0xcd, 0xcc,
	0x9b, 0xd7, 0x99, 0xf7, 0x5e, 0x16, 0x86, 0x45, 0x69, 0x2b, 0x3b, 0xa9, 0xd1, 0xac, 0x71, 0xfb,
	0xcd, 0x18, 0x11, 0x62, 0x61, 0xb3, 0x15, 0xa9, 0xd2, 0x66, 0xae, 0xac, 0x33, 0x9e, 0xa4, 0x9f,
	0x1e, 0x84, 0x2f, 0x4d, 0x25, 0x2e, 0xc1, 0x27, 0x1d, 0x7b, 0x89, 0x37, 0xee, 0xe7, 0x3e, 0x69,
	0x21, 0xa0, 0x63, 0xe4, 0x0a, 0x63, 0x9f, 0x11, 0xae, 0xc5, 0x08, 0x7a, 0x4b, 0xab, 0x64, 0x45,
	0xd6, 0xc4, 0x01, 0xe3, 0x6d, 0xdf, 0xcc, 0x94, 0x2c, 0xa4, 0xa2, 0x6a, 0x13, 0x77, 0x12, 0x6f,
	0x1c, 0xe6, 0x6d, 0x2f, 0x1e, 0xa0, 0x2f, 0x57, 0x68, 0xa8, 0x22, 0x74, 0x71, 0x98, 0x04, 0xe3,
	0xc1, 0xf4, 0x3a, 0xfb, 0xad, 0x26, 0x9b, 0x31, 0x69, 0x93, 0xef, 0xd9, 0x62, 0x08, 0xdd, 0xb5,
	0xc3, 0xf2, 0x8d, 0x74, 0x1c, 0xf1, 0xc5, 0xa8, 0x69, 0x9f, 0x74, 0xaa, 0xa0, 0xbb, 0xa3, 0x1f,
	0x93, 0xae, 0xac, 0x6e, 0xa5, 0x37, 0x75, 0x6b, 0x27, 0x38, 0xb0, 0x93, 0xc0, 0x40, 0xa3, 0x53,
	0x25, 0x15, 0xec, 0xa8, 0xc3, 0xa3, 0x43, 0x28, 0xfd, 0xf0, 0x40, 0x70, 0x3c, 0xcf, 0x05, 0x2a,
	0x7a, 0xa7, 0xbd, 0xd7, 0x36, 0x07, 0xef, 0x44, 0x0e, 0xfe, 0xa9, 0x1c, 0x82, 0xff, 0xe4, 0x90,
	0x1a, 0xe8, 0xe5, 0xe8, 0x0a, 0x6b, 0x1c, 0x8a, 0x09, 0x84, 0xcc, 0xe3, 0xdb, 0x83, 0xe9, 0xd5,
	0xb1, 0x15, 0xac, 0x3a, 0xdf, 0xf2, 0xc4, 0x1d, 0x44, 0x5c, 0xb8, 0xd8, 0xe7, 0xa3, 0x27, 0xfe,
	0xd8, 0x11, 0xa7, 0x0b, 0x38, 0xdf, 0x1a, 0xc7, 0xb2, 0x26, 0x85, 0xe2, 0x15, 0x2e, 0x1e, 0xc9,
	0xe8, 0x59, 0x2d, 0x69, 0x29, 0xe7, 0x4b, 0x14, 0xb7, 0x7f, 0xee, 0xf8, 0x91, 0xd5, 0xe8, 0xe6,
	0x18, 0xef, 0xdb, 0x4a, 0x7a, 0x36, 0x8f, 0xf8, 0x71, 0xde, 0x7f, 0x05, 0x00, 0x00, 0xff, 0xff,
	0x0e, 0x87, 0x16, 0x7f, 0xb7, 0x02, 0x00, 0x00,
}
