// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/campaign/campaign.proto

package go_micro_srv_campaign

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Campaign struct {
	Id                   string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Code                 string    `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Name                 string    `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description          string    `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Location             string    `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	Rewards              []*Reward `protobuf:"bytes,6,rep,name=rewards,proto3" json:"rewards,omitempty"`
	UserId               string    `protobuf:"bytes,7,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	VenueId              string    `protobuf:"bytes,8,opt,name=venue_id,json=venueId,proto3" json:"venue_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Campaign) Reset()         { *m = Campaign{} }
func (m *Campaign) String() string { return proto.CompactTextString(m) }
func (*Campaign) ProtoMessage()    {}
func (*Campaign) Descriptor() ([]byte, []int) {
	return fileDescriptor_campaign_8dc2bdc6ba0b9efb, []int{0}
}
func (m *Campaign) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Campaign.Unmarshal(m, b)
}
func (m *Campaign) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Campaign.Marshal(b, m, deterministic)
}
func (dst *Campaign) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Campaign.Merge(dst, src)
}
func (m *Campaign) XXX_Size() int {
	return xxx_messageInfo_Campaign.Size(m)
}
func (m *Campaign) XXX_DiscardUnknown() {
	xxx_messageInfo_Campaign.DiscardUnknown(m)
}

var xxx_messageInfo_Campaign proto.InternalMessageInfo

func (m *Campaign) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Campaign) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Campaign) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Campaign) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Campaign) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *Campaign) GetRewards() []*Reward {
	if m != nil {
		return m.Rewards
	}
	return nil
}

func (m *Campaign) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Campaign) GetVenueId() string {
	if m != nil {
		return m.VenueId
	}
	return ""
}

type Reward struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CampaignId           string   `protobuf:"bytes,2,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Available            int32    `protobuf:"varint,5,opt,name=available,proto3" json:"available,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Reward) Reset()         { *m = Reward{} }
func (m *Reward) String() string { return proto.CompactTextString(m) }
func (*Reward) ProtoMessage()    {}
func (*Reward) Descriptor() ([]byte, []int) {
	return fileDescriptor_campaign_8dc2bdc6ba0b9efb, []int{1}
}
func (m *Reward) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Reward.Unmarshal(m, b)
}
func (m *Reward) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Reward.Marshal(b, m, deterministic)
}
func (dst *Reward) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reward.Merge(dst, src)
}
func (m *Reward) XXX_Size() int {
	return xxx_messageInfo_Reward.Size(m)
}
func (m *Reward) XXX_DiscardUnknown() {
	xxx_messageInfo_Reward.DiscardUnknown(m)
}

var xxx_messageInfo_Reward proto.InternalMessageInfo

func (m *Reward) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Reward) GetCampaignId() string {
	if m != nil {
		return m.CampaignId
	}
	return ""
}

func (m *Reward) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Reward) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Reward) GetAvailable() int32 {
	if m != nil {
		return m.Available
	}
	return 0
}

type GetRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_campaign_8dc2bdc6ba0b9efb, []int{2}
}
func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (dst *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(dst, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

type Response struct {
	Created              bool        `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
	Campaign             *Campaign   `protobuf:"bytes,2,opt,name=campaign,proto3" json:"campaign,omitempty"`
	Campaigns            []*Campaign `protobuf:"bytes,3,rep,name=campaigns,proto3" json:"campaigns,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_campaign_8dc2bdc6ba0b9efb, []int{3}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCreated() bool {
	if m != nil {
		return m.Created
	}
	return false
}

func (m *Response) GetCampaign() *Campaign {
	if m != nil {
		return m.Campaign
	}
	return nil
}

func (m *Response) GetCampaigns() []*Campaign {
	if m != nil {
		return m.Campaigns
	}
	return nil
}

func init() {
	proto.RegisterType((*Campaign)(nil), "go.micro.srv.campaign.Campaign")
	proto.RegisterType((*Reward)(nil), "go.micro.srv.campaign.Reward")
	proto.RegisterType((*GetRequest)(nil), "go.micro.srv.campaign.GetRequest")
	proto.RegisterType((*Response)(nil), "go.micro.srv.campaign.Response")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for CampaignService service

type CampaignServiceClient interface {
	CreateCampaign(ctx context.Context, in *Campaign, opts ...client.CallOption) (*Response, error)
	GetCampaigns(ctx context.Context, in *GetRequest, opts ...client.CallOption) (*Response, error)
}

type campaignServiceClient struct {
	c           client.Client
	serviceName string
}

func NewCampaignServiceClient(serviceName string, c client.Client) CampaignServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "go.micro.srv.campaign"
	}
	return &campaignServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *campaignServiceClient) CreateCampaign(ctx context.Context, in *Campaign, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "CampaignService.CreateCampaign", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *campaignServiceClient) GetCampaigns(ctx context.Context, in *GetRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "CampaignService.GetCampaigns", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CampaignService service

type CampaignServiceHandler interface {
	CreateCampaign(context.Context, *Campaign, *Response) error
	GetCampaigns(context.Context, *GetRequest, *Response) error
}

func RegisterCampaignServiceHandler(s server.Server, hdlr CampaignServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&CampaignService{hdlr}, opts...))
}

type CampaignService struct {
	CampaignServiceHandler
}

func (h *CampaignService) CreateCampaign(ctx context.Context, in *Campaign, out *Response) error {
	return h.CampaignServiceHandler.CreateCampaign(ctx, in, out)
}

func (h *CampaignService) GetCampaigns(ctx context.Context, in *GetRequest, out *Response) error {
	return h.CampaignServiceHandler.GetCampaigns(ctx, in, out)
}

func init() {
	proto.RegisterFile("proto/campaign/campaign.proto", fileDescriptor_campaign_8dc2bdc6ba0b9efb)
}

var fileDescriptor_campaign_8dc2bdc6ba0b9efb = []byte{
	// 370 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0x4d, 0x4e, 0xf3, 0x30,
	0x10, 0xfd, 0xd2, 0x9f, 0x24, 0x9d, 0x54, 0xfd, 0x24, 0x4b, 0x08, 0x53, 0x51, 0xb5, 0x64, 0xd5,
	0x55, 0x90, 0xca, 0x82, 0x05, 0x62, 0xd5, 0x45, 0xd5, 0xad, 0xe9, 0x1e, 0xb9, 0xf1, 0xa8, 0xb2,
	0xd4, 0xc6, 0xc1, 0x4e, 0xc3, 0x29, 0xb8, 0x03, 0x17, 0xe1, 0x48, 0xdc, 0x01, 0xc5, 0xc1, 0x29,
	0x12, 0x54, 0x45, 0xec, 0x66, 0xde, 0xf3, 0x9b, 0xbc, 0x37, 0x8e, 0x61, 0x94, 0x6b, 0x55, 0xa8,
	0xeb, 0x94, 0xef, 0x72, 0x2e, 0x37, 0x59, 0x53, 0x24, 0x16, 0x27, 0x67, 0x1b, 0x95, 0xec, 0x64,
	0xaa, 0x55, 0x62, 0x74, 0x99, 0x38, 0x32, 0x7e, 0xf7, 0x20, 0x9c, 0x7f, 0x36, 0x64, 0x00, 0x2d,
	0x29, 0xa8, 0x37, 0xf1, 0xa6, 0x3d, 0xd6, 0x92, 0x82, 0x10, 0xe8, 0xa4, 0x4a, 0x20, 0x6d, 0x59,
	0xc4, 0xd6, 0x15, 0x96, 0xf1, 0x1d, 0xd2, 0x76, 0x8d, 0x55, 0x35, 0x99, 0x40, 0x24, 0xd0, 0xa4,
	0x5a, 0xe6, 0x85, 0x54, 0x19, 0xed, 0x58, 0xea, 0x2b, 0x44, 0x86, 0x10, 0x6e, 0x55, 0xca, 0x2d,
	0xdd, 0xb5, 0x74, 0xd3, 0x93, 0x5b, 0x08, 0x34, 0x3e, 0x73, 0x2d, 0x0c, 0xf5, 0x27, 0xed, 0x69,
	0x34, 0x1b, 0x25, 0x3f, 0x7a, 0x4d, 0x98, 0x3d, 0xc5, 0xdc, 0x69, 0x72, 0x0e, 0xc1, 0xde, 0xa0,
	0x7e, 0x94, 0x82, 0x06, 0x76, 0xa6, 0x5f, 0xb5, 0x4b, 0x41, 0x2e, 0x20, 0x2c, 0x31, 0xdb, 0x63,
	0xc5, 0x84, 0x96, 0x09, 0x6c, 0xbf, 0x14, 0xf1, 0x8b, 0x07, 0x7e, 0x3d, 0xe7, 0x5b, 0xda, 0x31,
	0x44, 0xee, 0x53, 0x95, 0xb0, 0x0e, 0x0d, 0x0e, 0x5a, 0x8a, 0x3f, 0x46, 0xbf, 0x84, 0x1e, 0x2f,
	0xb9, 0xdc, 0xf2, 0xf5, 0x16, 0x6d, 0xf6, 0x2e, 0x3b, 0x00, 0x71, 0x1f, 0x60, 0x81, 0x05, 0xc3,
	0xa7, 0x3d, 0x9a, 0x22, 0x7e, 0xf5, 0x20, 0x64, 0x68, 0x72, 0x95, 0x19, 0x24, 0x14, 0x82, 0x54,
	0x23, 0x2f, 0xb0, 0x36, 0x19, 0x32, 0xd7, 0x92, 0x3b, 0x08, 0x9d, 0x2d, 0x6b, 0x33, 0x9a, 0x8d,
	0x8f, 0xac, 0xcc, 0x5d, 0x2d, 0x6b, 0x04, 0xe4, 0x1e, 0x7a, 0xae, 0x36, 0xb4, 0x6d, 0x17, 0x7e,
	0x52, 0x7d, 0x50, 0xcc, 0xde, 0x3c, 0xf8, 0xef, 0xf0, 0x07, 0xd4, 0xa5, 0x4c, 0x91, 0xac, 0x60,
	0x30, 0xb7, 0xd6, 0x9a, 0x3f, 0xe9, 0xd4, 0xc4, 0xe1, 0xf8, 0xe8, 0x1d, 0xd7, 0xe9, 0xe3, 0x7f,
	0x64, 0x05, 0xfd, 0x05, 0x16, 0x4e, 0x61, 0xc8, 0xd5, 0x11, 0xc9, 0x61, 0x7f, 0xbf, 0x98, 0xba,
	0xf6, 0xed, 0x73, 0xb8, 0xf9, 0x08, 0x00, 0x00, 0xff, 0xff, 0x66, 0xfe, 0x1f, 0x37, 0x2f, 0x03,
	0x00, 0x00,
}
